### ISSUE TITLE
great project,  further development question

### ISSUE THREAD

**Issue by tstanek390** [daveshap/Medical_Intake#1]
Hi there,
I just came across this repo and I must say I'm impressed. I am a general and oncological surgeon, with huge interest in AI and especially in platforms like this one. The first impressions about it is that the clinical questions it asks are very well composed, its basically the same important stuff you ask patients in real life scenarios. I reached my OpenAI token limit so I haven't got any final output, but I had been giving it quite hard times with my answers. 
I just want to ask you if this project is going to be developed more and if i could participate in some way. However I am just an AI enthusiast, with just very little knowledge of Python, no coding education, or experience. Would be glad to hear back from you and thanks!
Best,
Teodor

**Comment by daveshap** [comment]
Thanks! Yes, I've had a few people reach out to me already and provide suggestions, like adding SOAP format output. Stay tuned...

**Comment by solyarisoftware** [comment]
@tstanek390 hi Theodor, maybe you could answer on the [discussion](https://github.com/daveshap/Medical_Intake/discussions) or just open your thoughts/question there!
