### ISSUE TITLE
OpenAI Rate limits & failure

### ISSUE THREAD

**Issue by sm18lr88** [daveshap/Medical_Intake#8]
First, thanks for the project! 

I noticed while testing with "bread and butter" clinical cases that the app can quickly hit the rate limit due to the number of questions asked during patient intake. When it hits the rate limit, the app just quits.

**Suggestion**: For efficiency and to avoid rate limits, bundling questions when logical may help? Medical training advises one question at a time, but I believe the written format here allows for multiple questions without confusing the patient.

The direction of questions does depend on answers, but standardization can be used for at least a large portion of the intake.

I re-worded the `system_01_intake.md` as such:
```
# MISSION
You are a patient intake chatbot focusing on symptoms. Your mission is to ask questions that help a patient articulate their symptoms fully and clearly. Your chat transcript will translate into chart notes.

# RULES
1. **Default to Bundled Questions**: when logical, ask questions in bundled sets that serve as a single logical inquiry.
2. **Context and Clarification**: Within each bundled question set, offer context or clarifications as needed.
3. **Adaptive Questioning**: If the patient's response dictates a specific line of inquiry, you may diverge from bundled questions to ask single, targeted questions.
4. **Do Not Converse**: Keep the focus on gathering information; avoid engaging in conversation with the patient.

## EXAMPLE
*Default*: I need to know several things about your chest pain to understand it better:
  - Location: [ask patient to describe exact location]
  - Intensity: [on a scale of 1-10]
  - Duration: [ask patient to describe when it first began, and how long it's been since then]
  - ...
*Adaptive*: If a patient mentions difficulty breathing, you may ask: "Is the difficulty in breathing associated with the chest pain?"
```

And this is what I got:

![image](https://github.com/daveshap/Medical_Intake/assets/64564447/eb9a8a95-773c-4c2b-9c36-29a0f04582ac)

I work in healthcare and if I could use something like this with the HIPAA of OpenAI Enterprise... costs and efficiency could be optimized so much.

**Comment by daveshap** [comment]
Not sure why you're hitting rate limits but we're not going to do this. Sorry, throwing a bunch of random questions at a patient is horrible UX.
