### ISSUE TITLE
Rate limit reached for 10KTPM-200RPM

### ISSUE THREAD

**Issue by bukhanka** [daveshap/Medical_Intake#9]
Had this error on intake stage
How could I avoid it?
I responded in Russian to the chat, it might be the case?
Any way to optimize prompts?

Error communicating with OpenAI: "Rate limit reached for 10KTPM-200RPM in organization org-gvAzf6Q9pR7y2UAiI9owd3LF on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues."

**Comment by daveshap** [comment]
Sorry but this goes outside the scope of this project. I recommend you follow the instructions provided by the error message.

**Comment by bukhanka** [comment]
Thank anyway Dave! Apreciate your work here and on channel!
